name: truck_management_mobile
description: Flutter UI for Truck Management System.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.12
  flutter_dotenv: ^5.1.0
  shared_preferences: 2.5.5
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  flutter_local_notifications: ^22.3.0
  image_picker: ^1.1.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/branding/logo_icon.png"

flutter:
  uses-material-design: true
  assets:
    - app.env
    - assets/branding/logo_icon.png
